### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by buckettybabe** [coderdurga/ACDH-Flight-Booking-#12]
Our original plan was to have thank you page (ie. third page) but its not part of our wireframe diagrams.  If we have time, quickly produce one.  Probably doesn't matter as we have already submitted that part of the project.

**Comment by hooimingwong** [comment]
There is a thank you page in the wireframe folder, we can still show them on the slides 😉

**Comment by buckettybabe** [comment]
Great thanks Hooi.  Could you please send third page of wireframe to Chaitanya in Slack?
